name: Pre-Submit (Database)
on:
  workflow_call:

jobs:
  changes:
    runs-on: [ubuntu-latest]
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/presubmit_unit_tests.yml'
              - 'database/**/*.ts'

  unit-tests:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./database
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run test
