name: presubmit
on:
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  database:
    uses: ./.github/workflows/presubmit_database.yml

  orange_money:
    uses: ./.github/workflows/presubmit_orange_money.yml

  markdown:
    uses: ./.github/workflows/presubmit_markdown.yml

  spellcheck:
    uses: ./.github/workflows/presubmit_spellcheck.yml

  yaml:
    uses: ./.github/workflows/presubmit_yaml.yml
