name: Pre-Submit (Spellcheck)
on:
  workflow_call:

jobs:
  changes:
    runs-on: [ubuntu-latest]
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '**/*.md'
              - '**/*.txt'
              - '.github/workflows/presubmit_spellcheck.yml'

  misspell:
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          exclude: |
            **/package-lock.json

  languagetool:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
