name: Pre-Submit (Database)
on:
  workflow_call:

jobs:
  changes:
    runs-on: [ubuntu-latest]
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/presubmit_unit_tests.yml'
              - 'database/**/*.ts'

  unit-tests:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./database
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.0.0
          cache: "npm"
          cache-dependency-path: "database/package-lock.json"
      - run: npm ci
      - run: npm run test
